# Generated by Django 4.2.6 on 2023-10-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='persona_perl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admRrhh.persona'),
        ),
    ]
