# Generated by Django 4.2.6 on 2023-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0002_personal_persona_perl'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='estado_perl',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
